### ISSUE TITLE
IMPORT FOREIGN SCHEMA

### ISSUE THREAD

**Issue by davidfetter** [EnterpriseDB/mysql_fdw#21]
...is not yet implemented.

This would be super handy now, even though it's a 9.5 feature.

**Comment by jjthiessen** [comment]
I've implemented initial support for this in my [import-foreign-schema](https://github.com/jjthiessen/mysql_fdw/tree/import-foreign-schema) branch.

It does rely on the changes made in my [PG_95](https://github.com/jjthiessen/mysql_fdw/tree/PG_95) branch as well (even though it isn't rebased onto it). I wasn't sure whether you guys wanted to archive the current `master` as a historical branch and make `master` 9.5+ only (like what was done for PostgreSQL 9.3 (_i.e.,_ the `PG_92` split)); or whether you wanted to use version checks in the source to enable version-specific features (which is why I've kept the changes separate for now).

**Comment by ibrarahmad** [comment]
I think version check is OK for all new features.

On Thu, Jun 25, 2015 at 12:42 AM, jjthiessen <notifications@github.com>
wrote:

> I've implemented initial support for this in my import-foreign-schema
> <https://github.com/jjthiessen/mysql_fdw/tree/import-foreign-schema>
> branch.
>
> It does rely on the changes made in my PG_95
> <https://github.com/jjthiessen/mysql_fdw/tree/PG_95> branch as well (even
> though it isn't rebased onto it). I wasn't sure whether you guys wanted to
> archive the current master as a historical branch and make master 9.5+
> only (like what was done for PostgreSQL 9.3 (*i.e.,* the PG_92 split));
> or whether you wanted to use version checks in the source to enable
> version-specific features (which is why I've kept the changes separate for
> now).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/mysql_fdw/issues/21#issuecomment-114990379>
> .
>



-- 
Ibrar Ahmed

**Comment by ahsanhadi** [comment]
I agree. It is better to have version check in the code.

**Comment by jjthiessen** [comment]
Please see pull-request https://github.com/EnterpriseDB/mysql_fdw/pull/62.

**Comment by ahsanhadi** [comment]
This merge request is committed...
