### ISSUE TITLE
ERROR: failed to prepare the MySQL query

### ISSUE THREAD

**Issue by xieyuheng1025** [EnterpriseDB/mysql_fdw#230]
Commands out of sync； you can‘t run this command now

**Comment by surajkharage19** [comment]
Thank you @xieyuheng1025 for reporting this issue.

It would be helpful if you provide below additional details to understand the issue:
1. What version of MySQL is being used?
2. Are you getting this issue reproduced consistently?
3. Complete reproducible test case
4. What happens when you run the same query on some other foreign table of the same MySQL server?
5. Previously, we have seen that this kind of issue occurs when Dolt (MySQL compatible DB) is used. Are you using this kind of DB?

**Comment by surajkharage19** [comment]
Hi @xieyuheng1025,

We have not received any further updates on this from your end. We are happy to assist if you provide the required details.
If the issue is resolved then can you please close the case from your end?

**Comment by xieyuheng1025** [comment]
Mysql version 8.0.23，Long transaction pull data still error
