### ISSUE TITLE
Unable to get text in Chinese via mysql_fdw

### ISSUE THREAD

**Issue by tom10271** [EnterpriseDB/mysql_fdw#313]
I tried to create server with and without setting character_set 'utf8mb4'
```sql
CREATE SERVER rds FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host 'my-rds.us-west-2.rds.amazonaws.com', port '3306');
CREATE SERVER rds FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host 'my-rds.us-west-2.rds.amazonaws.com', port '3306', character_set 'utf8mb4');
```

However result selected for value contains Chinese is all displayed as `?`.
<img width="1245" alt="Screenshot 2024-09-26 at 5 06 10 PM" src="https://github.com/user-attachments/assets/8c39c8ca-aee7-417b-8fba-3ec55b43e393">

**Comment by surajkharage19** [comment]
Hi @tom10271,

Would it be possible for you to share additional details about this issue so that we can help you better?

- What is the encoding setting on MySQL and Postgres database? I mean these Chinese chars are getting displayed properly on MySQL side?
- The other tables (without mysql_fdw) able to display the Chinese chars on the Postgres side? this will give us the information about this is something specific to mysql_fdw or Postgres in general. Sometimes Postgres client_encoding is not set correctly and the chars do not get displayed.
- If you strongly suspect that this is specific to mysql_fdw then please share one simple reproducible test case for the same along with some sample data.

**Comment by tom10271** [comment]
Would it be possible for you to share additional details about this issue so that we can help you better?

 - What is the encoding setting on MySQL and Postgres database? I mean these Chinese chars are getting displayed properly on MySQL side?
  - Yes it is displaying properly using utf8mb4

 - The other tables (without mysql_fdw) able to display the Chinese chars on the Postgres side? this will give us the information about this is something specific to mysql_fdw or Postgres in general. Sometimes Postgres client_encoding is not set correctly and the chars do not get displayed.
   - All tables contains Chinese characters become `?`


However I do have a solution by setting `character_set 'utf8'`
https://github.com/EnterpriseDB/mysql_fdw/issues/2#issuecomment-2376609881

It seems auto is not really working.

**Comment by surajkharage19** [comment]
Thanks for the update @tom10271.

As mentioned by you, after setting character_set to `utf8`, you can able to see characters correctly.
Please let us know if you need further assistance on this.

**Comment by tom10271** [comment]
Thank you for providing support. Yeah everything solved and working fine, just would be great if this fdw would work out of the box. Not sure why the default auto is not working which would be confusing to other.
