### ISSUE TITLE
Relative date comparisons

### ISSUE THREAD

**Issue by phillbaker** [EnterpriseDB/mysql_fdw#52]
Thanks for all the hard work! I'm trying to execute queries with where clauses using relative timestamps. However, it looks like because the mysql and postgres time subtraction approaches are different, this isn't working: I'm receiving errors like `ERROR: failed to prepare the MySQL query: FUNCTION mysql_fdw.now does not exist. `. 

[Although the where clauses are pushed down to Mysql](https://github.com/EnterpriseDB/mysql_fdw#where-clause-push-down), using mysql-only functions appears does not appear to work either: `ERROR: function date_sub(timestamp with time zone, interval) does not exist`.

For example, in mysql a relevant query would be:
```
CREATE TABLE `foos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

SELECT count(*)
FROM foos
WHERE created_at > date_sub(NOW(), INTERVAL '30' DAY);
```

On the postgres side, the query in straight postgres syntax would be:
```
SELECT count(*)
FROM alpha.foos
WHERE created_at > now() - interval '30' DAY;
```

I've taken a look at https://github.com/EnterpriseDB/mysql_fdw/issues/42, but it seems like this might be a separate issue.

cc @supershabam

**Comment by ahsanhadi** [comment]
This is already fixed in the latest code...


edb=# explain verbose SELECT count(*)
FROM foos
WHERE created_at > now() - interval '30' DAY;
2015-04-14 17:54:48 PKT LOG:  statement: explain verbose SELECT count(*)
	FROM foos
	WHERE created_at > now() - interval '30' DAY;
                                            QUERY PLAN                                             
---------------------------------------------------------------------------------------------------
 Aggregate  (cost=26.00..26.01 rows=1 width=0)
   Output: count(*)
   ->  Foreign Scan on public.foos  (cost=25.00..26.00 rows=1 width=0)
         Output: id, created_at
         Remote server startup cost: 25
         Remote query: SELECT NULL FROM `test`.`foos` WHERE ((`created_at` > (now() - '30 days')))
(6 rows)

edb=#
